// <auto-generated />
using BoardGameHub.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BoardGameHub.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BoardGameHub.Domain.Entities.Jogos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Additional")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayerNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("db_Jogos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Additional = "Variações de tabuleiro, cartas de desenvolvimento, recursos (madeira, trigo, lã, etc.)",
                            Category = "Estratégia",
                            Description = "Catan é um jogo de estratégia no qual os jogadores competem para construir colônias e expandir seu território em uma ilha fictícia.",
                            ImageUrl = "https://example.com/catan-image",
                            Name = "Catan",
                            PlayerNumber = 3
                        },
                        new
                        {
                            Id = 2,
                            Additional = "Varios modos, diferentes edições temáticas, cartas de sorte/azar.",
                            Category = "Clássico/Negócio",
                            Description = "Monopólio é um jogo clássico de negociação imobiliária no qual os jogadores compram, vendem e trocam propriedades para acumular riqueza e falir os seus adversários.",
                            ImageUrl = "https://example.com/monopoly-image",
                            Name = "Monopólio",
                            PlayerNumber = 2
                        },
                        new
                        {
                            Id = 3,
                            Additional = "Tabuleiros assimétricos, cartas de objetivos, miniaturas de unidades.",
                            Category = "Estratégia",
                            Description = "Scythe é um jogo de estratégia ambientado em uma realidade alternativa dos anos 1920, onde os jogadores controlam facções e competem pela supremacia em uma terra devastada pela guerra.",
                            ImageUrl = "https://example.com/scythe-image",
                            Name = "Scythe",
                            PlayerNumber = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
